version: '3.9'
services:
  datascience-notebook:
    build: 
      # Make the parent project the root directory instead of this one.
      context: ../
      # Use the Dockerfile in the environment directory
      dockerfile: environment/Dockerfile
    # Map port 8888 in the container to port 10000 on the host machine.
    # This is what makes jupyter accessible at localhost:10000
    ports:
      - "10000:8888"
    volumes:
      # This connects the Jupyter notebook directory to the host machine so
      # that can all be checked into version control.
      - '../analysis:/home/jovyan/'
      - '../data:/home/jovyan/data'
      - './jupyter_server_config.py:/home/jovyan/.jupyter/jupyter_server_config.py'
